### ISSUE TITLE
Automation - arm away

### ISSUE THREAD

**Issue by YanivKrit** [AlexxIT/XiaomiGateway3#1018]
what service I need to call in order to arm away the xiaomi_gateway3,
I want  to create an automation that sends notification with a button to "Arm Away" the xiaomi gateway 3

```
alias: Alarm on notification
description: ""
trigger: []
condition: []
action:
  - device_id: [device_id]
    domain: mobile_app
    type: notify
    message: Senario activated, do you want to activate the alarm?
    title: Home alarm
    data:
      actions:
        - action: TURN_ON
          title: Turn On
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: TURN_ON
    timeout: "00:05:00"
    continue_on_timeout: false  
  - service: xiaomi_gateway3.send_command
    data:
      host: 192.168.x.x
      command: armed_away
      data: Data
mode: single
```

**Comment by YanivKrit** [comment]
found the solution:


```
alias: Alarm on notification
description: ""
trigger: []
condition: []
action:
  - device_id: [device_id]
    domain: mobile_app
    type: notify
    message: Senario activated, do you want to activate the alarm?
    title: Home alarm
    data:
      actions:
        - action: TURN_ON
          title: Turn On
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: TURN_ON
    timeout: "00:05:00"
    continue_on_timeout: false
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.xxxx_alarm
mode: single
```
