### ISSUE TITLE
BLE locks attribute to change sensor state.

### ISSUE THREAD

**Issue by sykiat89** [AlexxIT/XiaomiGateway3#120]
Hey! Thanks for supporting the xiaomigateway 3 for HA! 
I have tested the first gen Mijia Smart Door Lock (MJZNMS02LM) and it worked as intended. 

My purpose is to try to expose the smart door lock in HomeKit. 
To my limited knowledge, the BLE devices fire "events" and it is stateless. So, to expose the door lock in HomeKit, i would need to somehow "convert" the event into a binary sensor. Ive managed to do so with the following code:

```
binary_sensor:
  - platform: template
    sensors:
      door_lock_inverse:
        friendly_name: "Door Lock Status Inverse"
        device_class: "door"
        value_template: "{{ is_state_attr('sensor.e6b4db4bf59a_action', 'action', 'lock')and is_state_attr('sensor.e6b4db4bf59a_action', 'action_id', 1)}}"
        
      door_lock:
        friendly_name: "Door Lock Status"
        device_class: "door"
        value_template: "{{ is_state('binary_sensor.door_lock_inverse', 'off')}}"      
```

But im not able to retain the state as new event will quickly overwrite the previous state. Any pointers?
