### ISSUE TITLE
How to override device_class upon one entity

### ISSUE THREAD

**Issue by latel** [AlexxIT/XiaomiGateway3#1272]
I've a device with MAC A4:C1:38:3C:00:16, which have a entity `sensor.a4c1383c0016_formaldehyde` with device_class `formaldehyde`:

```yaml
state_class: measurement
native_value: 0.01
unit_of_measurement: mg/m³
device_class: formaldehyde
friendly_name: xiaofei Formaldehyde
```

but ha's homebridge does not support this yet, so I have to override device_class to `volatile_organic_compounds`, and change unit from mg/m3 to ug/m3 with a multiplication of 1000, I tried this configuration:

```yaml
xiaomi_gateway3:
  devices:
    "a4c1383c0016":
      entities:
        formaldehyde: "volatile_organic_compounds"
```

I inspect this entity in ha's developer tool, however there is no difference, device_class is still `formaldehyde`.

**Comment by latel** [comment]
using homeassistant native override features is enough. I also used unit conversion.

```yaml
template:
  - sensor:
      - name: "sensor.a4c1383c0016_ch2o"
        unique_id: "sensor.a4c1383c0016_ch2o"
        unit_of_measurement: "µg/m³"
        device_class: "volatile_organic_compounds"
        state_class: "measurement"
        state: >
          {{ (states('sensor.a4c1383c0016_formaldehyde') | float * 1000) | int }}
        availability: "{{ states('sensor.a4c1383c0016_formaldehyde') not in ['unknown', 'unavailable', 'none'] }}"
        attributes:
          friendly_name: "bedroom formaldehyde"
```
