### ISSUE TITLE
Unable to set occupancy_timeout for Aqara Motion Sensor in configuration.yaml

### ISSUE THREAD

**Issue by donald-ong** [AlexxIT/XiaomiGateway3#1334]
The detection keep clearing off in 90 seconds to 2 min, despite I have made the configuration to timeout in 30 mins. Please advise.

In configuration.yaml file,
```
xiaomi_gateway3:
  devices:
    "00:15:8d:00:05:4b:90:38":
      occupancy_timeout: 1800
```

The MAC address retrieved from xiaomi_gateway3.log,
...
2024-04-20 00:47:42,058 {'uid': '0x00158d00054b9038', 'did': 'lumi.158d00054b9038', 'msg': 'init_device', 'data': {'did': 'lumi.158d00054b9038', 'type': 'zigbee', 'ieee': '00:15:8d:00:05:4b:90:38', 'nwk': '0xc198', 'fw_ver': 0, 'hw_ver': 0, 'cloud_name': 'M Toilet - Motion Sensor', 'cloud_fw': '1.0.0_0000', 'market_brand': 'Aqara', 'market_name': 'Motion Sensor', 'market_model': 'RTCGQ11LM'}}
...

**Comment by AlexxIT** [comment]
```
xiaomi_gateway3:
  devices:
    "0x00158d00054b9038":
      occupancy_timeout: 1800
```
