### ISSUE TITLE
Support yunmi.kettle.v12

### ISSUE THREAD

**Issue by FilipeOS** [AlexxIT/XiaomiGateway3#1350]
I have finally upgraded my lumi.gateway.mgl03 (Gateway: ZNDMWG03LM, ZNDMWG02LM, YTC4044GL) to custom 1.5.6_0001 and my kettle (BLE: MJHWSHO2YM, yunmi.kettle.v12) now show this unknown sensors.

Is there any way to make them work please?

```
extra:
  cloud_fw: 4.1.0_0003
  cloud_name: Kettle
  did: blt.4.1bqt9mXXXg01
  mac: a4:c1:XXXX8:2b
  market_brand: Xiaomi
  market_model: MJHWSHO2YM, yunmi.kettle.v12
  market_name: Kettle Pro
  rssi_54ef44cd65bf: -71
  type: ble
last_seen:
  54eXXXd65bf: 2m19s
listeners: 5
model: 2528
params: {}
ttl: 1h5m
uid: a4c13XXX82b
```

![download](https://github.com/AlexxIT/XiaomiGateway3/assets/18313286/44a95423-8269-4ce5-a2ee-ad36f6635437)

It would be awesome if we could remotely enable the last keep warm setting (make it warm, not boil)
