### ISSUE TITLE
xiaomi_gateway3.send_command on version 4.x

### ISSUE THREAD

**Issue by azuwis** [AlexxIT/XiaomiGateway3#1354]
After upgrade to version 4.0.3, got some errors in `home-assistant.log`:

```
... Error executing script. Service not found for call_service at pos 1: Service xiaomi_gateway3.send_command not found
```

I use this automation to run some command when homeassistant or the gateway startup:

```
- trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.xxxxxxxxxxxx_gateway
      to: "on"
  action:
    service: xiaomi_gateway3.send_command
    data:
      command: miio
      host: <ip>
      data: >-
        {"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"1; <command>"}}
```

Is there any equivalent service I can use on version 4.x?
