### ISSUE TITLE
Support loock.lock.t2pv1 

### ISSUE THREAD

**Issue by zhang-wenchao** [AlexxIT/XiaomiGateway3#1359]
```
extra:
  cloud_fw: 2.1.9_1040
  cloud_name: 门锁
  did: '1059779105'
  mac: 53:f0:fb:8f:55:9c
  rssi_54ef445ea159: -53
  type: ble
last_seen:
  54ef445ea159: 12m5s
listeners: 3
model: 9815
params: {}
ttl: 1h5m
uid: 53f0fb8f559c
```
