### ISSUE TITLE
Add support Mi Body Composition Scale S400

### ISSUE THREAD

**Issue by razor-4eg** [AlexxIT/XiaomiGateway3#1388]
Cant figure out how to create a converter for Xiaomi Scale s400 BLE

here the device info:
```
extra:
  cloud_fw: 2.1.1_0057
  cloud_name: Body Composition Scale
  did: blt.3.1i0oijp3sk400
  mac: 84:46:93:20:07:0a
  market_brand: Xiaomi
  market_model: 12505, yunmai.scales.ms103
  market_name: Body Scale s400
  rssi_54ef4437c787: -62
  seq: 24
  type: ble
last_seen:
  54ef4437c787: 1m6s
listeners: 5
model: 12505
params: {}
ttl: 1h5m
uid: 84469320070a
```
Here is debug logs with it (blt.3.1i0oijp3sk400)
[debug.log](https://github.com/user-attachments/files/15936930/debug.log)
