### ISSUE TITLE
Lights randomly switch on and off

### ISSUE THREAD

**Issue by sulliwane** [AlexxIT/XiaomiGateway3#1415]
Hi,

**Setup:** I'm using the HA version `2024.6.1` with Xiaomi Smart Home Hub 2 (192.168.1.10) (China version).
![Screenshot from 2024-08-04 10-32-31](https://github.com/user-attachments/assets/42a63207-7f24-4bbe-9cea-2213adb5bccc)

**Issue:** I had one or two lights that were randomly switching on (ie: by themselves, NOT me pressing any buttons) at very random hours (morning, evening, middle of the night).

It was very annoying, so I decided to remove all the lights from the MiJia App, and re-add them all. Thinking it would solve the problem. Worse, now all the lights can randomly switch on by themselves.

**Frequency**: I'd say it's once every 8 to 12 hours that one light switches on. random time. 

One example below: As you can see on the lamp history chart, it triggered 'by itself' the first three times. And the last 2 times are the logs of me pressing two times the lamp button.

![ha lamp randomly switch on](https://github.com/user-attachments/assets/f53932f4-a64c-4ccc-8635-a8e19cf0143a)

I suspect Xiaomi server to remotely (because of a bug) switch on my lights (I will try to block HA from accessing internet for some days to see if it fixes the problem. If not it means it's 100% local issue).

I'd really appreciate any help to investigate this issue 🙏

Here are some more data regarding that lamp:

```
extra:
  cloud_fw: 1.4.0_0005
  cloud_name: Scene mesh color temperature lamp 3
  did: '1093442001'
  mac: cc:b5:d1:d1:2f:ea
  market_brand: LeMesh
  market_model: lemesh.light.wy0c08
  market_name: Mesh Light
  rssi_54ef44471fae: -89
  type: mesh
last_report:
  brightness: 196.35
  color_temp: 186
  dimming: Immediately
  light: true
  mode: WY
  night_light: false
  power_on_state: 'on'
  save_state: true
last_report_gw:
  fw_ver: 1.0.7_0019
  host: 192.168.1.10
  mac: 54:ef:44:57:1f:ae
  model: lumi.gateway.mcn001
  name: Xiaomi Smart Home Hub 2
last_report_ts: 6s
last_request_ts: 6s
last_seen:
  54ef44471fae: 8s
listeners: 5
model: 3531
params:
  brightness: 196.35
  color_temp: 186
  dimming: Immediately
  light: true
  mode: WY
  night_light: false
  power_on_state: 'on'
  save_state: true
ttl: 50m
uid: ccb5d2d12fea
```
And here are all my integrations (in case it's useful):
![image](https://github.com/user-attachments/assets/ae6fc1e0-7621-46c3-abd2-68dbe06a8c10)
