### ISSUE TITLE
Xiaomi Light Sensor GZCGQ01LM works but the value is off

### ISSUE THREAD

**Issue by mikephemera** [AlexxIT/XiaomiGateway3#1419]
the Light Sensor GZCGQ01LM works with Gateway DMWG03LM Firmware 1.0.6_0016. It reports lux and update is all working.
But I notice that the value is off.
This is local value it reports from Xiaomi Gateway 3 Integration.
<img width="419" alt="image" src="https://github.com/user-attachments/assets/f041312e-1850-4e6d-9eab-99efb07eb553">
This is cloud value it reports from Xiaomi Miot Auto and Mi home app. This is accurate.
<img width="409" alt="image" src="https://github.com/user-attachments/assets/06804837-89f5-423e-9945-629a6cd4c3d0">

The shape is good so I downloaded the values and run regressions on both data. It's roughly a nature log curve. Not sure if it's a bug or just me. I tried to delete everything and add them back. It's the same. Technically it still could work with Template conversion.
![image](https://github.com/user-attachments/assets/9d09accb-ebf9-4387-ada6-ea777206047d)
<img width="178" alt="image" src="https://github.com/user-attachments/assets/7de066e6-1478-4f91-afd8-199709ceed19">

**Comment by AlexxIT** [comment]
Well. I have tested my version. The values are exactly the same as in the MiHome app.

```
extra:
  fw_ver: 21
  hw_ver: 0
  lqi: 124
  market_brand: Xiaomi
  market_model: GZCGQ01LM, YTC4043GL
  market_name: Light Sensor EU
  nwk: '0x3b23'
  rssi: -69
  seq: 21
  type: zigbee
last_report:
  illuminance: 265
last_report_gw:
  fw_ver: 1.0.8_0001
  model: lumi.gateway.mcn001
  name: Gateway 29
last_report_ts: 1m29s
listeners: 4
model: lumi.sen_ill.mgl01
params:
  illuminance: 265
  nwk: 15139
ttl: 2h50m
```
