### ISSUE TITLE
Can Xiaomi Multimode Gateway 2 FW version 1.0.7_0019 be used for ZHA?

### ISSUE THREAD

**Issue by Huiyuen07** [AlexxIT/XiaomiGateway3#1525]
I have a Xiaomi Multimode Gateway 2 with firmware version 1.0.7 and sucessfully got the key via uart and setup the integration, but I cannot setup via ZHA for zigbee control. It showed unknow errors occurs or connection fails (sth like that as the interface is in Chinese). My aim is use the device as a zigbee controller for multiple vendors' product.  Anything I should do before setup ZHA? Do I need to flash any other firmware? Thanks.

Device Information
```
extra:
  cloud_fw: 1.0.7_0019
  cloud_name: Xiaomi Smart Home Hub 2
  did: '499189137'
  fw_ver: 1.0.7_0019
  mac: 54:ef:44:43:ef:10
  mac2: 18:C2:3C:06:1D:3F
  market_brand: Xiaomi
  market_model: ZNDMWG04LM, BHR6765GL
  market_name: Multimode Gateway 2 EU
  rssi: -13
  type: gateway
last_report:
  channel: 0
last_report_gw:
  fw_ver: 1.0.7_0019
  host: 192.168.1.91
  mac: 54:ef:44:43:ef:10
  model: lumi.gateway.mgl001
  name: Xiaomi Smart Home Hub 2
last_report_ts: 1m
last_request_ts: 1m
last_seen: {}
listeners: 3
model: lumi.gateway.mgl001
params:
  brightness: 255.0
  channel: 0
  led: true
  power_tx: 0
ttl: 0s
uid: 54ef4443ef10
```
![image](https://github.com/user-attachments/assets/0cd44415-00bf-440b-bca9-12a13c43a1a1)
