### ISSUE TITLE
MJWSD05MMC not appearing correctly

### ISSUE THREAD

**Issue by MaticSulc** [AlexxIT/XiaomiGateway3#1540]
I've successfully extracted the key for lumi.gateway.mgl001 with firmware 1.0.7_0019. I have connected WXKG01LM (wireless switch) to it, and it integrated perfectly - I can detect clicks, trigger events ...

I want to add MJWSD05MMC now - but it's not showing up correctly. It only allows me to trigger "Device info".
![image](https://github.com/user-attachments/assets/3c16e1be-9394-47f3-ba79-060518193014)

This is the data, I receive when I trigger the device info command.
```
extra:
  cloud_fw: 2.0.0_0005
  cloud_name: Xiaomi Smart Temperature and Humidity Monitor 3
  did: blt.4.1k4p74jdpgk00
  mac: a4:c1:38:e5:ca:b2
  rssi_54ef4458be2b: -52
  seq: 124
  type: ble
last_seen:
  54ef4458be2b: 31m30s
listeners: 3
model: 19527
params: {}
ttl: 1h5m
uid: a4c138e5cab2
```

Am I missing something? Does my HA need to have BLE support in order for me to get data, or can I use the hub to get that data?
