### ISSUE TITLE
Add support lemesh.light.wy0d02

### ISSUE THREAD

**Issue by hzonz** [AlexxIT/XiaomiGateway3#1553]
Device: Lemesh Color Temperature Lights Ultra
Model: lemesh.light.wy0d02
Support: Turn on/off, adjust brightness and color temperature.
More Information:  
[https://home.miot-spec.com/spec/lemesh.light.wy0d02](url)

```
from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
    19733: ["LeMesh", "Lemesh Color Temperature Lights Ultra", "lemesh.light.wy0d02"],
    "spec": [
        BaseConv("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2", max=100),
        ColorTempKelvin("color_temp", mi="2.p.3", mink=2700, maxk=6500),
        MapConv("mode", "select", mi="2.p.7", map={0: "None", 4: "Day", 5: "Night", 7: "Warmth", 8: "Tv", 9: "Reading", 10: "Computer", 11: "Hospitality", 12: "Entertainment", 13: "Wakeup", 14: "Dusk", 15: "Sleep", 16: "Custom1", 17: "Custom2", 18: "Custom3", 19: "Custom4", 20: "Eye Protection", 21: "Breath", 22: "Beat", 23: "Rhythm"}),
        MapConv("power_on_state", "select", mi="2.p.9", map={0: "Default", 1: "ON", 2: "OFF"}),
        BoolConv("flex_switch", "switch", mi="2.p.12", entity=ENTITY_CONFIG),
        BoolConv("night_light", "switch", mi="2.p.13", entity=ENTITY_CONFIG),
        BoolConv("rhythm_switch", "switch", mi="7.p.7", entity=ENTITY_CONFIG),
    ],  
}] + DEVICES
```

The parameters are consistent with 17687: ["LeMesh", "Scene Mesh Light V2S Pro", "lemesh.light.wy0c24"].

BoolConv("flex_switch", "switch", mi="2.p.12", entity=ENTITY_CONFIG), BoolConv("night_light", "switch", mi="2.p.13", entity=ENTITY_CONFIG), BoolConv("rhythm_switch", "switch", mi="7.p.7", entity=ENTITY_CONFIG),
These three switches are not functioning correctly.

Debug log:
```
{'topic': 'miio/report', 'data': b'{"id":1977224921,"method":"_async.stat","params":{"version":1,"btstat_props":[{"did":"793531810","siid":2,"aiid":0,"piid":13,"control_type":2,"from":"4","rpc_addr":0,"control_times":1,"total":100,"cost":100,"ret":0,"result":0},{"did":"793531810","siid":7,"aiid":0,"piid":1,"control_type":2,"from":"4","rpc_addr":0,"control_times":1,"total":300,"cost":100,"ret":0,"result":0},{"did":"793531810","siid":2,"aiid":0,"piid":13,"control_type":2,"from":"4","rpc_addr":0,"control_times":1,"total":0,"cost":0,"ret":0,"result":0}]}}'}
 {'topic': 'miio/report', 'data': b'{"id":586052922,"method":"properties_changed","params":[{"did":"793531810","siid":2,"piid":13,"tid":1,"value":false}],"type":16}'}
 {'uid': '8446935abadb', 'did': '793531810', 'msg': 'on_report', 'data': {'night_light': False}}
{'topic': 'miio/report', 'data': b'{"id":1476567923,"method":"_async.stat","params":{"version":1,"btstat_props":[{"did":"793531810","siid":2,"aiid":0,"piid":13,"control_type":2,"from":"4","rpc_addr":0,"control_times":1,"total":100,"cost":100,"ret":0,"result":0}]}}'}
{'topic': 'miio/report', 'data': b'{"id":302434924,"method":"properties_changed","params":[{"did":"793531810","siid":2,"piid":13,"tid":2,"value":false}],"type":16}'}
{'uid': '8446935abadb', 'did': '793531810', 'msg': 'on_report', 'data': {'night_light': False}}

```

**Comment by 2331892928** [comment]
This works well, but without the state of the lamp, the state of the lamp is unknown

**Comment by 2331892928** [comment]
Please ask: mi 2.p.1 where did I come from I also want to write my own support device

**Comment by Johnnybyzhang** [comment]
Mine is showing up as and "Unknown Mesh" in the integration, it seems to work with "Xiaomi Miot Auto", but I still prefer local control over cloud any time. Please let me know if there's anything I can help with bringing support to this model.
```
extra:
  did: '888152669'
  mac: ac:8c:46:63:0b:36
  rssi_54ef446ef1cd: -87
  seq: 94
  type: mesh
last_report:
  switch: false
last_report_gw:
  fw_ver: 1.0.8_0001
  host: 192.168.1.168
  mac: 54:ef:44:6e:f1:cd
  model: lumi.gateway.mcn001
  name: Xiaomi Smart Home Hub 2
last_report_ts: 36s
last_request_ts: 35s
last_seen:
  54ef446ef1cd: 25m12s
listeners: 2
model: 19733
params:
  switch: false
ttl: 50m
uid: ac8c46630b36
```
