### ISSUE TITLE
Add support Xiaomi Motion Sensor s2, model 19552

### ISSUE THREAD

**Issue by 7424ff** [AlexxIT/XiaomiGateway3#1601]
Hi.

Could you please add support / check support for Xiaomi Motion Sensor s2?
It looks fine in the Xiaomi Home app, but HA XiaomiGateway3 integration shows as unknown device. 
No commands or triggers available.

I am using HA with version Core 2025.4.4 and Xiaomi Multimode Gateway 2 (EU) (ZNDMWG04LM, BHR6765GL, lumi.gateway.mgl001) with 1.0.7_0019 firmware.

Thanks for your help.

```
extra:
  cloud_name: Xiaomi Motion Sensor 2S - Kitchen
  did: blt.4.1l5pu1sitgk00
  mac: 6c:fd:22:64:b8:d7
  rssi_54ef444bbb6f: -60
  seq: 124
  type: ble
last_seen:
  54ef444bbb6f: 12s
listeners: 2
model: 19552
params: {}
ttl: 1h5m
uid: 6cfd2264b8d7
```
