### ISSUE TITLE
Add support for Sonoff ZBMINI2

### ISSUE THREAD

**Issue by avbor** [AlexxIT/XiaomiGateway3#1619]
Info from integration:
```
extra:
  did: lumi.8b95ffffeec6863
  fw_ver: 16
  hw_ver: 0
  ieee: 08:b9:5f:ff:fe:ec:68:63
  lqi: 116
  nwk: '0x3c03'
  rssi: -71
  seq: 121
  type: zigbee
last_report:
  model: ZBMINIR2
last_report_gw:
  fw_ver: 1.0.7_0019
  host: 192.168.10.185
  mac: 54:ef:44:46:7e:78
  model: lumi.gateway.mgl001
  name: CH Mi Hub 2 01
last_report_ts: 1m59s
last_seen:
  54ef44467e78: 1m59s
listeners: 4
model: ZBMINIR2
params:
  fw_ver: 16
  model: ZBMINIR2
ttl: 2h50m
uid: '0x08b95ffffeec6863'
```
