### ISSUE TITLE
Add support for IKEA E1525/E1745

### ISSUE THREAD

**Issue by avbor** [AlexxIT/XiaomiGateway3#1621]
https://www.zigbee2mqtt.io/devices/E1525_E1745.html#ikea-e1525%252Fe1745
```
extra:
  did: lumi.b4e3f9fffea02607
  fw_ver: 32
  hw_ver: 0
  ieee: b4:e3:f9:ff:fe:a0:26:07
  lqi: 84
  nwk: '0xcc09'
  rssi: -79
  seq: 216
  type: zigbee
last_report:
  battery: 100
  battery_voltage: 3000
last_report_gw:
  fw_ver: 1.0.7_0019
  host: 192.168.10.185
  mac: 54:ef:44:46:7e:78
  model: lumi.gateway.mgl001
  name: CH Mi Hub 2 01
last_report_ts: 3m25s
last_request_ts: 3m
last_seen:
  54ef44467e78: 1m44s
listeners: 6
model: TRADFRI motion sensor
params:
  battery: 100
  battery_voltage: 3000
  fw_ver: 32
  model: TRADFRI motion sensor
ttl: 2h50m
uid: '0xb4e3f9fffea02607'
```
