### ISSUE TITLE
Cover service.toggle problem

### ISSUE THREAD

**Issue by uPagge** [AlexxIT/XiaomiGateway3#166]
Hello

I have I have aqara curtains b1. And I faced the following problem

After some time, apparently, the position of the curtains is reset, the cover.toggle service also stops working

To fix this, you have to go into lovelace, and move the curtain position slider. After that, service.toggle starts working successfully. But after a while everything breaks down again

**Comment by AlexxIT** [comment]
Probably related to #139
Or you can show logs with error

**Comment by uPagge** [comment]
and where to look at the logs, there seems to be nothing in the usual log

**Comment by AlexxIT** [comment]
Wait new version with fix for 139. Maybe it helps

**Comment by uPagge** [comment]
@AlexxIT Unfortunately the update didn't work for me. But I noticed another peculiarity. Toggle only stops working when the curtains are open. If the curtains are closed, even all night, the toggle will work in the morning. But in the evening the toggle does not close the curtains. Have to send position for curtains

**Comment by AlexxIT** [comment]
Check device state in developer tools when get the problem. There should be something like this:

```yaml
current_position: 50
friendly_name: Aqara Curtain B1 Motor
supported_features: 15
```

**Comment by uPagge** [comment]
I apologize for missing. Curtains for some unknown reason do not store their history, maybe the problem is

![изображение](https://user-images.githubusercontent.com/40397740/108807015-570d8900-75b4-11eb-8fc7-5abf167cde25.png)

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/108814155-5defc800-75c3-11eb-9cbb-a1ca44543edd.png)

I reconnected the curtains and they started to keep history. Until I called toggle again

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/108814559-1453ad00-75c4-11eb-83e9-128c6db749e0.png)

Another observation. I reconnect the curtains open, then call toggle. The curtains close, then I call toggle the curtains open, but the curtains are closed. After that, toggle stops working

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/108815008-ce4b1900-75c4-11eb-85dd-cfb83b5c839d.png)

As I said before, toggle stops working only after the curtains are opened. If the curtains are closed, then the toggle works.

If you call toggle when the curtains are closed, then the curtains open, and all this time their status is opened, but as soon as they open completely, the status changes to closed

**Comment by uPagge** [comment]
I tried to do a life hack and open the curtains to 99 and 1 positions. To build on these numbers, but as soon as the curtain opens up to these positions, it resets the position to 0 and writes that it is closed (

**Comment by uPagge** [comment]
The temporary fix I am using. Maybe someone will come in handy

```
cover:
    input_boolean:
    
        cover_fix:
            name: Cover Open
    
    switch:
        - platform: template
          switches:
            cover_bedroom:
                friendly_name: 'Cover'
                value_template: "{{ is_state('input_boolean.cover_fix', 'on') }}"
                turn_on:
                    - service: cover.set_cover_position
                      entity_id: cover.bedroom
                      data:
                        position: 100
                    - service: input_boolean.turn_off
                      data:
                        entity_id: input_boolean.cover_fix
                turn_off:
                    - service: cover.set_cover_position
                      entity_id: cover.bedroom
                      data:
                        position: 0
                    - service: input_boolean.turn_on
                      data:
                        entity_id: input_boolean.cover_fix
        
    automation:
    
        - alias: 'Open and Close Cover Opple'
          trigger:
            - platform: state
              entity_id: sensor.0x04cf8cdf3c7974cc_action
              to: 'button_5_hold'
          action:
            - service: switch.toggle
              entity_id: switch.cover_bedroom
```
