### ISSUE TITLE
Button WXKG01LM doesn't work work in automation

### ISSUE THREAD

**Issue by l0ckk** [AlexxIT/XiaomiGateway3#25]
Hello!
Button WXKG01LM is detected in HA as "sensor.0x158d000407e8a4_action". Clicks are shown in main panel, but in automation it doesn't work ((
Example of code:
`  alias: test2
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d000407e8a4_action
      click_type: single
  condition: []
  action:
  - data: {}
    entity_id: light.yeelight_650
    service: light.turn_on
 `

**Comment by mbratukha** [comment]
Try to use **state** instead of **event**:

```yaml
entity_id: sensor.0x158d0003d4751b_action
platform: state
to: single
```
