### ISSUE TITLE
Aqara Opple Scene Switch Action state is permanent

### ISSUE THREAD

**Issue by Zuz666** [AlexxIT/XiaomiGateway3#43]
Hi!

For Aqara Opple Scene Switch (WXCJKG11LM/WXCJKG12LM/WXCJKG13LM) action sensor state attributes does not change to empty after the event if fired.
For example after a single press on the second switch's button the state of sensor look like this permanently (until the next button is pressed):
```yaml
button_2: 1
action: button_2_single
friendly_name: Aqara Opple Six Button Action
```
I'm new to Home Assistant, and I'm not sure that this behavior is correct.
It's not a problem to use Code-RED integration and handle "press" events from there or use some condition templates in HA but this looks like a problem and requires your attention or explanation.
