### ISSUE TITLE
Xiaomi Button (WXKG01LM) state problem

### ISSUE THREAD

**Issue by gigidu94** [AlexxIT/XiaomiGateway3#45]
The Xiaomi Button (WXKG01LM) is keeping the same state, and is not going back to the empty state.

Can you fix it please ?

Best regards

**Comment by Zuz666** [comment]
@gigidu94 please check [documentation](https://github.com/AlexxIT/XiaomiGateway3#handle-button-actions)! This is the expected behavior.
Just use trigger like this:
```yaml
automation:
- alias: Turn off all lights
  trigger:
  - platform: state
    entity_id: sensor.0x158d0002fa99fd_action
    to: button_1_single
  action:
  - service: light.turn_off
    entity_id: all
  mode: single
```
