### ISSUE TITLE
Aqara Magic Cube - the actual side it was flipped to

### ISSUE THREAD

**Issue by rfvermut** [AlexxIT/XiaomiGateway3#475]
Currently MiHome integration reports `flip90` event without any additional details.

<details>
  <summary>raw event</summary>

```
{
    "event_type": "state_changed",
    "data": {
        "entity_id": "sensor.0x158d00054b8644_action",
        "old_state": {
            "entity_id": "sensor.0x158d00054b8644_action",
            "state": "",
            "attributes": {
                "action": "flip90",
                "friendly_name": "Aqara Cube Action",
                "icon": "mdi:bell"
            },
            "last_changed": "2021-10-02T18:55:36.433942+00:00",
            "last_updated": "2021-10-02T18:55:36.433942+00:00",
            "context": {
                "id": "7834e9f5119e8990f803994f10580fe9",
                "parent_id": null,
                "user_id": null
            }
        },
        "new_state": {
            "entity_id": "sensor.0x158d00054b8644_action",
            "state": "flip90",
            "attributes": {
                "action": "flip90",
                "friendly_name": "Aqara Cube Action",
                "icon": "mdi:bell"
            },
            "last_changed": "2021-10-02T18:55:36.989665+00:00",
            "last_updated": "2021-10-02T18:55:36.989665+00:00",
            "context": {
                "id": "745c3bf1444ac1e9331a09d89b72e676",
                "parent_id": null,
                "user_id": null
            }
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-10-02T18:55:36.989665+00:00",
    "context": {
        "id": "745c3bf1444ac1e9331a09d89b72e676",
        "parent_id": null,
        "user_id": null
    }
}
```
</details>

Looking at ZHA blueprints cube also reports the `activated_face`, `relative_degrees` and reacts to `knock` command. See https://community.home-assistant.io/t/aqara-magic-cube-zha-51-actions/270829

<details>
  <summary>code sample, see  trigger.event.data.args.*</summary>

```
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input 'remote'
action:
  - variables:
      command: '{{ trigger.event.data.command }}'
      value: '{{ trigger.event.data.args.value }}'
      flip_degrees: '{{ trigger.event.data.args.flip_degrees }}'
      relative_degrees: '{{ trigger.event.data.args.relative_degrees }}'
      flip_90: !input 'flip_90'
      flip_180: !input 'flip_180'
      slide_any_side: !input 'slide_any_side'
      knock_any_side: !input 'knock_any_side'
      flip90: 64
      flip180: 128
      slide: 256
      knock: 512
      shake: 0
      drop: 3
      activated_face: "\n{% if command == \"slide\" or command == \"knock\" %}\n\n \
      \ {% if trigger.event.data.args.activated_face == 1 %} 1\n\n  {% elif trigger.event.data.args.activated_face\
      \ == 2 %} 5\n\n  {% elif trigger.event.data.args.activated_face == 3 %} 6\n\n\
      \  {% elif trigger.event.data.args.activated_face == 4 %} 4\n\n  {% elif trigger.event.data.args.activated_face\
      \ == 5 %} 2\n\n  {% elif trigger.event.data.args.activated_face == 6 %} 3\n\n\
      \  {% endif %}\n\n{% elif command == 'flip' %}\n\n  {{ trigger.event.data.args.activated_face\
      \ | int }}\n\n{% endif %}\n"
      from_face: "\n{% if command == \"flip\" and flip_degrees == 90 %}\n\n  {{ ((value\
      \ - flip90 - (trigger.event.data.args.activated_face - 1)) / 8) + 1 | int }}\n\
      \n{% endif %}\n"
```
</details>

I would love to help and fix it myself, just nudge me in the right direction.
