### ISSUE TITLE
Motion sensor status update problem

### ISSUE THREAD

**Issue by HepoH3** [AlexxIT/XiaomiGateway3#48]
As I understand it, the motion sensor in the assistant receives data from the gateway only when motion is detected. Then a timer starts and then it automatically sets the sensor to off. There is a problem with this logic.
When I go to the motion sensor and do something in front of it, it doesn't go into a “no motion” state until I’m gone for two minutes. And since it will not go into this state, it will not send a "there is motion" message to HA when the timer expires. So, if I do something longer than the timer, the sensor in the assistant will go into 'no motion' state and will not leave it until I leave for two minutes. And if I'll configure light automation on this sensor, it will simply turn light off while I work, and will not turn it back, even if I start jumping in front of the sensor.
Is there ability to recieve 'no motion' message from gateway and controll sensor without program timer?

**Comment by Zuz666** [comment]
@HepoH3  you can change  occupancy timeout for motion sensor:
```yaml
xiaomi_gateway3:
  devices:
    '0x158d00044c5dff':
      occupancy_timeout: 90  # (optional) default 90 seconds
```
