### ISSUE TITLE
Aqara Switches and Chinese server + HA Automations

### ISSUE THREAD

**Issue by digitalsteezdesign** [AlexxIT/XiaomiGateway3#56]
Hey there AlexxIT,

First of all thanks for your continuous development. I use the latest version of your Gateway 3 integration with Firmware 1.4.6_0012, keeping it on chinese server
I’ve also got a stable installation in Docker HOME ASSISTANT on my QNAP TS-251.

I have a bunch of WXKG03LM (Single) , WXKG07LM (double) & an QBKG22LM (Wall) which after the updates (not sure if integration update or automatic firmware update), don't seem to work very well, anylonger. The actions are rarely seen or triggered (single press, double press) and it creates non-functionality with my HA, can't use the switches.

My question is, by holding it onto the Chinese server, could it produce such delays that the automations/triggers get confused into home assistant? If i switch (From MI APP), i guess the Token will be reset and i will have to add the Gateway to the Integration again right?
If i switch on Europe, will the Aqara Switches remain paired and still be able to pair Extra through the Integration (because through the app I won't be able to)?

More details about my setup:
I use HUE Bridge to control the Tradfri Bulbs and a small set of HUE Bulbs. (Needed it especially for pairing the Theater lights with the Philips HUE TV light)
Then i Bought this XIAOMI GATEWAY3 zndmwg03lm (initially just to test it), which i hold for the moment on Chinese server (afraid to switch to Europe as from the iOS MiAPP will make the AQara switches un-pairable).
So there you go, on the XIAOMI, since it has Zigbee 3.0 and better BLE, i will be holding Mi 360 Camera, Aqara switches, Moving Sensors, Smoke detector, etc.
As HA HUE Integration accepts HUE Groups, i can control the group or the individual bulbs.

**Comment by digitalsteezdesign** [comment]
I found out that by configuring for example a simple Group of three lights and activating them in single Automation mode:
While i am trying to use a Single Automation, per Switch, covering all States( Single, Double, button_1_single, button_2_single
```
entity_id: sensor.0x158d0002ca0bf1_action
from: single
platform: state
then
data: {}
entity_id: light.office
service: light.toggle

```
It works well, while the below is a bit “unresponsive” - works few times.
(this is for a double switch)
```
entity_id: sensor.0x158d0005426548_action
platform: state
choose:
  - conditions:
      - condition: state
        entity_id: sensor.0x158d0005426548_action
        state: button_1_single
    sequence:
      - data: {}
        entity_id: light.living_masa
        service: light.toggle
  - conditions:
      - condition: state
        entity_id: sensor.0x158d0005426548_action
        state: button_2_single
    sequence:
      - data: {}
        entity_id: light.living_canapea
        service: light.toggle
default: []
```
I don’t seem to get how to configure these. Maybe with event or template but i don’t get it yet.
