### ISSUE TITLE
Transition support for Bluetooth Mesh Lights

### ISSUE THREAD

**Issue by deskoh** [AlexxIT/XiaomiGateway3#748]
Bluetooth mesh lights `YLTS04YL` / `YLTS03YL` does not seem to support `transition` when turning on.

Component version: `v2.0.10 - 2022-04-28`
Firmware: `v1.5.0_0102`

```
- service: light.turn_on
  data:
    brightness: 255
    entity_id: ...
    transition: 180
```
