### ISSUE TITLE
Can't see mi humidity and temperature

### ISSUE THREAD

**Issue by jehy** [AlexxIT/XiaomiGateway3#753]
Hi! I can't undersand how to get humidity and temperature from sensor on my HA dashboard. I successfully connected my xiaomi 3 gateway but nothing really happens.

`Home Assistant Core` 2022.5.3
`Gateway 3` version 1.5.1_0032
Sensor `LYWSDCGQ/01ZM` is connected to gateway via BLE via Mi app
`XiaomiGateway3` installed yesterday from github master branch.
No errors in home assistant log

device info from integration:
```
Name: mi Temperature & humidity sensor
Model: cleargrass.sensor_ht.dk1
MAC: 58:2D:34:36:F0:C5
Bindkey: Not needed
```

gateway info from integration:
```
Name: Gateway
Model: lumi.gateway.mgl03
IP: 192.168.66.29
MAC: 54:EF:44:2E:F3:34
Token: ***
```

I already tried adding it to configuration yaml like this:
```
xiaomi_gateway3:
  devices:
      "58:2D:34:36:F0:C5":
        entities:
          temperature: sensor
          humidity: sensor
```

But nothing happend, no new entities added and no new sensor on my dashboard.
But I can see sensor measurements from MI app on gateway page so I'm sure that sensor is connected to gateway.

On my keenetic city router, I disabled `Airtime Fairness` and I don't have option `256-QAM`. Gateway is connected to china mainland server.

What am I missing?
То ли я тупой, то ли лыжи не едут :)
