### ISSUE TITLE
Config occupancy_timeout

### ISSUE THREAD

**Issue by alexv190** [AlexxIT/XiaomiGateway3#97]
У меня есть датчик движения с id 'binary_sensor.reaction_xiaomi_motion_1_motion', прописываю для него такой конфиг
```
xiaomi_gateway3:
  devices:
    'binary_sensor.reaction_xiaomi_motion_1_motion':
      occupancy_timeout: 20  # (optional) default 90 seconds
```

Перезагружаю HA. Время реакции датчика не меняется. Пробовал прописать id без кавычек и еще пробовал 'reaction_xiaomi_motion_1_motion', не помогает.
Как таки добиться результата?
